package org.mclavo;

import java.util.stream.Collectors;

/**
 * Renders Java source code for generated {@link BeanDefinition} implementations based on a {@link DefinitionSpec}.
 */
public final class DefinitionSourceRenderer {

    private static final String DEFINITION_TEMPLATE =
    """
    package %s;

    %s

    // Synthetic class generated by Jet annotation processor. Do not edit.
    public final class %s implements BeanDefinition<%s> {

        private final ScopeProvider<%s> provider =
            ScopeProvider.singletonScope(beanProvider -> %s);

        @Override
        public %s apply(BeanProvider beanProvider) {
            return provider.apply(beanProvider);
        }

        @Override
        public Class<%s> type() {
            return %s.class;
        }

        @Override
        public Qualifier qualifier() {
            return %s;
        }

        @Override
        public boolean primary() {
            return %s;
        }
    }
        
    """;
    
    /**
     * Builds the full source code for a generated definition class.
     *
     * @param spec metadata used to render package, imports, class name and creation logic
     * @return Java source code for the generated definition class
     */
    public static String render(DefinitionSpec spec) {
        String importsBlock = spec.getImports().stream()
            .sorted()
            .map(importName -> "import " + importName + ";")
            .collect(Collectors.joining("\n"));
        
        String isPrimary = spec.isPrimary() ? "true" : "false";

        return DEFINITION_TEMPLATE.formatted(
            // package
            spec.getPackageName(),
            // imports
            importsBlock,
            // class
            spec.getSimpleClassName(),
            spec.getBeanType(),
            // provider
            spec.getBeanType(),
            spec.getCreationExpression(),
            // apply
            spec.getBeanType(),
            // type
            spec.getBeanType(),
            spec.getBeanType(),
            // qualifier
            spec.getQualifierExpression(),
            // primary
            isPrimary
        );
    }
}
