/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mclavo;

import org.mclavo.context.ControlTower;
import org.mclavo.context.JetContext;

public class App {
    
    public static void main(String[] args) {
        JetContext context = ControlTower.run(App.class);
        MyApplication app = context.provide(MyApplication.class);
        EmptyBean emptyBeanInstance = context.provide(EmptyBean.class);
        SimplePart part = context.provide(SimplePart.class);
/*         Service s1 = jetFactory.getInstanceOf(Service.class, "Hello Jet!");
        s1.send();
        
        Service s2 = jetFactory.getInstanceOf(Service.class);
        s2.send();
        
        MyApplication app = jetFactory.getInstanceOf(MyApplication.class); */
        System.out.println("MyApplication has been created with a Service: " + app.isServiceSet());
        System.out.println("EmptyBean has been created: " + emptyBeanInstance.getMessage());
        System.out.println("SimplePart has been created: " + part.getMessage());
    }
}
