/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mclavo;

import org.mclavo.factory.JetFactory;

public class App {

    public static void main(String[] args) {

        JetFactory jetFactory = JetFactory.INSTANCE;
        
        Service s1 = jetFactory.getInstanceOf(Service.class, "Hello Jet!");
        s1.send();
        
        Service s2 = jetFactory.getInstanceOf(Service.class);
        s2.send();
        
        MyApplication app = jetFactory.getInstanceOf(MyApplication.class);
        System.out.println("MyApplication has been created with a Service: " + app.isServiceSet());
    }
}
